### ISSUE TITLE
bug: demo project does not start without libxcb-xinerama-so.0 being installed

### ISSUE THREAD

**Issue by mcdurdin** [achille-martin/pyqt-crom#34]
Following the steps as given in the README, we encountered core dump trying to run the demo at step 1.4.4.

This gives a solution: https://askubuntu.com/questions/1298645/shared-library-not-found-for-pyqt5-libxcb-xinerama-so-0-not-found

```
sudo apt install libxcb-xinerama0
```

**Comment by achille-martin** [comment]
Interesting, I mentioned this issue in [v1.0.0](https://github.com/achille-martin/pyqt-crom/tree/v1.0.0?tab=readme-ov-file#setup-in-virtualbox-optional) and how to troubleshoot it.

When I created [v2.0.0](https://github.com/achille-martin/pyqt-crom/tree/v2.0.0) and tested it with a fresh build, I didn't encounter any problem with `Qt`.

I can re-add the fix suggestion to the [troubleshooting note](https://github.com/achille-martin/pyqt-crom/blob/main/doc/troubleshooting/common_issues.md).

What is your setup? (python, OS, virtual machine?, ubuntu, etc.)

Thanks for your contribution!

**Comment by mcdurdin** [comment]
1.

```
(pyqt-crom-env) sandy@pyqt-crom:~/pyqt-crom/examples/demo/demo_project/demo_pkg$ python3 demo_app.py 
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.

Aborted (core dumped)
```

2. Brand new Ubuntu 22.04 VM, following steps in README
3. No
4. Yes, although it was later in the install when we had trouble with Qt that we went back and retried (after other external deps installed)

**Comment by achille-martin** [comment]
I have created a [PR](https://github.com/achille-martin/pyqt-crom/pull/35) to fix the instructions:
* Added instruction to install libxcb-xinerama0 to fix issue with Qt5.15 and xcb plugin
* Added generic way to debug Qt plugin errors to troubleshoot note

Please double-check if you wish and I'll merge.

Thanks again
