### ISSUE TITLE
Thank you!!!

### ISSUE THREAD

**Issue by Kalmat** [achille-martin/pyqt-crom#45]
My first PyQt app for Android... It's alive!!!!

Just wanted to let you know that this helped me A LOT! After hours following countless and indecipherable guides, videos, blogs and other similar stuff with no success... I found this. You're a geek, pal.

Thank you for sharing and helping.

**Comment by achille-martin** [comment]
Hi @Kalmat,

That is an amazing news!

Thank you for sharing your feedback too!

I am currently trying to figure out the thorny issue spotted in https://github.com/achille-martin/pyqt-crom/issues/32. So if you get to that stage, come lend a hand ;)
